### PR TITLE
[WIP] 100xQuest: A platform to Unlock Your Potential 

### PR DESCRIPTION
**Pull request by ItsFlash10**
Its a work in progress.

PS: Most of the logic related to test is done which is similar to what we get in JEE NTA portal. The wireframe UI is complete(almost), feel free to check it [here](https://aptitude-test-web.vercel.app/) and share feed back. Working on the UI and the BE part atm.

cc: @hkirat

### CODE REVIEW

**Comment by Smnthjm08** [comment]
damn!, really nice with the full screen feature.

**Comment by ItsFlash10** [comment]
> damn!, really nice with the full screen feature.

Thanks!! xD

**Comment by VenkataBhaskarr** [comment]
Submission is redirecting to 404 not found page!! 
Also add payment option.

**Comment by ItsFlash10** [comment]
> Submission is redirecting to 404 not found page!! Also add payment option.

Ser I have already mentioned in the title that this PR is a [WIP] work in progress :)

**Comment by hkirat** [comment]
Closing this but can u copy over the logic of rzp to main now?

**Comment by ItsFlash10** [comment]
> Closing this but can u copy over the logic of rzp to main now?

Will do!

**Pull request closed without merging**
