### PR TITLE
Initialise - Landing, Auth, Exams, Results

### PR DESCRIPTION
**Pull request by vanshavenger**
Hey @hkirat 
Live Link for above for your reference: https://apti-test.vercel.app/ 
(Login with Email/Password, or Google, or Github for now, Discord secret and id not setup for prod)

The following PR contains:
1. Auth -> With argon2, OAuth - Google, Github, Discord
2. Landing page
3. Next js with server actions
4. Prisma
5. docker to setup it locally
6.  Husky for pre commits
7.  Shadcn Ui 

I am happy to make changes if you have in mind and make it the best possible for everyone, will try everything to give back to you. :)))

Images are shared below:
Screenshot 2024-08-25 at 4 12 18 AM
Screenshot 2024-08-25 at 4 12 07 AM
Screenshot 2024-08-25 at 4 12 01 AM
Screenshot 2024-08-25 at 4 11 57 AM
Screenshot 2024-08-25 at 4 11 50 AM
Screenshot 2024-08-25 at 4 11 38 AM
Screenshot 2024-08-25 at 4 10 24 AM
Screenshot 2024-08-25 at 4 10 12 AM
Screenshot 2024-08-25 at 4 09 57 AM

### CODE REVIEW

**Comment by ItsFlash10** [comment]
Good work dude

**Comment by VenkataBhaskarr** [comment]
It will be perfect if you add payments, else looks good.

**Comment by vanshavenger** [comment]
> It will be perfect if you add payments, else looks good.

Yess , but still ii feel ui ux and functionality should be made more better, and my stripe and razorpay accounts idk why not working so will take harkirat help on it

**Comment by Ashutoshpadhi629** [comment]
nice work dude @vanshavenger

**Comment by vanshavenger** [comment]
Added Charts to make it more appealing
Screenshot 2024-08-25 at 2 40 30 PM
Screenshot 2024-08-25 at 2 40 05 PM

**Pull request merged**
