### PR TITLE
Working on the project [currently doing the test page]

### PR DESCRIPTION
**Pull request by YadlaMani**

### CODE REVIEW

**Comment by YadlaMani** [comment]
image
Landing page

**Comment by YadlaMani** [comment]
image

login page

**Comment by YadlaMani** [comment]
image
Test initilization page

**Comment by YadlaMani** [comment]
@hkirat, please check out the website. It's still a work in progress, so feedback is appreciated.

**Comment by VenkataBhaskarr** [comment]
Deploy your website and provide the link so it would be better to give feedback.

**Comment by hkirat** [comment]
Closing in favor of https://github.com/code100x/aptitude-test/pull/11

**Pull request closed without merging**
